### ISSUE TITLE
Break out splunk apps for zipkin into separate project

### ISSUE THREAD

**Issue by msennett9** [tmartin14/zipkin-demo#2]
I think the Splunk apps for Zipkin would be worth separating from the Javascript demo of the zipkin.  We want to use these Splunk apps (on-prem) and don't need the rest of the project.  Others might also and changes could more cleanly be contributed back.

**Comment by tmartin14** [comment]
The zipkin app is the only one that is not already available on Splunkbase.  I may break the zipkin out in the future, but for now this is where it lives.   Sorry for the inconvenience.
